package nl.ljack2k.axecellent.chainsaw;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import nl.ljack2k.axecellent.Axecellent;

/**
 * The tags that drive this mod. Everything Axecellent does is decided by these
 * three - there is no item to craft and no enchantment to apply, so a pack
 * changes behaviour purely by editing tag JSON.
 * <p>
 * Defaults are generated by the datagen providers ({@code datagen/}) and can be
 * replaced or extended by any datapack:
 * <ul>
 *   <li>{@link Items#CHAINSAW} defaults to {@code #minecraft:axes}</li>
 *   <li>{@link Blocks#CHAINSAW_LOGS} defaults to {@code #minecraft:logs}</li>
 *   <li>{@link Blocks#CHAINSAW_LEAVES} defaults to {@code #minecraft:leaves}</li>
 * </ul>
 * Adding to a tag is additive across datapacks, so a pack can grant the chainsaw to
 * one more tool without copying the whole default list.
 */
public final class ModTags {
    private ModTags() {
    }

    public static final class Items {
        private Items() {
        }

        /** Tools that cut a whole tree in one break. THE tag this mod exists for. */
        public static final TagKey<Item> CHAINSAW = TagKey.create(
                Registries.ITEM, ResourceLocation.fromNamespaceAndPath(Axecellent.MODID, "chainsaw"));
    }

    public static final class Blocks {
        private Blocks() {
        }

        /** Blocks treated as trunk: the search spreads through these and they count against maxLogs. */
        public static final TagKey<Block> CHAINSAW_LOGS = TagKey.create(
                Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(Axecellent.MODID, "chainsaw_logs"));

        /** Blocks treated as canopy: cleared after the logs, and never counted against maxLogs. */
        public static final TagKey<Block> CHAINSAW_LEAVES = TagKey.create(
                Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(Axecellent.MODID, "chainsaw_leaves"));
    }
}
