package nl.ljack2k.axecellent.chainsaw;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;
import nl.ljack2k.axecellent.Axecellent;
import org.jetbrains.annotations.Nullable;

/**
 * The tags that drive this mod. Everything Axecellent does is decided by these - there is no
 * item to craft and no enchantment to apply, so a pack changes behaviour purely by editing tag
 * JSON (or a KubeJS script, or anything else that can add to a tag).
 * <p>
 * Defaults are generated by the datagen providers ({@code datagen/}) and can be replaced or
 * extended by any datapack. Adding to a tag is additive across datapacks, so a pack can grant
 * the chainsaw to one more tool without copying anyone else's list.
 * <p>
 * <b>The tool tags.</b> Four of them, all shipping empty:
 * <ul>
 *   <li>{@link Items#CHAINSAW} - cuts trees, using whatever {@link Config#MODE} says.</li>
 *   <li>{@link Items#CHAINSAW_PROGRESSIVE}, {@link Items#CHAINSAW_HELD},
 *       {@link Items#CHAINSAW_INSTANT} - cuts trees in that specific mode, whatever the
 *       config says.</li>
 * </ul>
 * A mode tag <em>implies</em> the chainsaw, so granting a tool a specific mode is one line
 * rather than two. This is what lets the modes be a progression across tool materials - a
 * wooden axe that makes you work for it, a netherite axe that does it for free - instead of one
 * server-wide choice that leaves two modes permanently unused.
 */
public final class ModTags {
    private ModTags() {
    }

    public static final class Items {
        private Items() {
        }

        /** Tools that cut a whole tree, in the mode {@link Config#MODE} selects. */
        public static final TagKey<Item> CHAINSAW = itemTag("chainsaw");

        /** Tools pinned to {@link CutMode#PROGRESSIVE}, ignoring the configured default. */
        public static final TagKey<Item> CHAINSAW_PROGRESSIVE = itemTag("chainsaw_progressive");

        /** Tools pinned to {@link CutMode#HELD}. */
        public static final TagKey<Item> CHAINSAW_HELD = itemTag("chainsaw_held");

        /** Tools pinned to {@link CutMode#INSTANT}. */
        public static final TagKey<Item> CHAINSAW_INSTANT = itemTag("chainsaw_instant");

        private static TagKey<Item> itemTag(String path) {
            return TagKey.create(Registries.ITEM,
                    ResourceLocation.fromNamespaceAndPath(Axecellent.MODID, path));
        }
    }

    public static final class Blocks {
        private Blocks() {
        }

        /** Blocks treated as trunk: the search spreads through these and they count against maxLogs. */
        public static final TagKey<Block> CHAINSAW_LOGS = blockTag("chainsaw_logs");

        /** Blocks treated as canopy: cleared with the log they hang from, never counted as logs. */
        public static final TagKey<Block> CHAINSAW_LEAVES = blockTag("chainsaw_leaves");

        private static TagKey<Block> blockTag(String path) {
            return TagKey.create(Registries.BLOCK,
                    ResourceLocation.fromNamespaceAndPath(Axecellent.MODID, path));
        }
    }

    /** Does this item cut trees at all - through any of the four tool tags? */
    public static boolean isChainsaw(ItemStack stack) {
        return pinnedMode(stack) != null || stack.is(Items.CHAINSAW);
    }

    /**
     * The mode this tool cuts in: its pinned mode if it has one, otherwise the configured
     * default. Returns null only for a tool that is not a chainsaw at all.
     */
    @Nullable
    public static CutMode modeFor(ItemStack stack) {
        CutMode pinned = pinnedMode(stack);
        if (pinned != null) {
            return pinned;
        }
        return stack.is(Items.CHAINSAW) ? Config.MODE.get() : null;
    }

    /**
     * The mode tag this tool sits in, or null for none.
     * <p>
     * A tool in more than one mode tag is a pack mistake with no sensible answer, so the order
     * here is simply fixed and documented rather than clever: the first match wins, most
     * hands-on mode first.
     */
    @Nullable
    private static CutMode pinnedMode(ItemStack stack) {
        if (stack.is(Items.CHAINSAW_HELD)) {
            return CutMode.HELD;
        }
        if (stack.is(Items.CHAINSAW_PROGRESSIVE)) {
            return CutMode.PROGRESSIVE;
        }
        if (stack.is(Items.CHAINSAW_INSTANT)) {
            return CutMode.INSTANT;
        }
        return null;
    }
}
